### ISSUE TITLE
Final touches to website

### ISSUE THREAD

**Issue by akshatvg** [CodeChefVIT/Photify-DEVSOC#1]
Please ensure the following changes are made so the site can be made available for a production environment:
- Add favicon and apple-touch-icon.
- Edit README with the official [CodeChef-VIT Template](https://github.com/CodeChefVIT/template).
- Add meta tags for good SEO.
- Add a sitemap.
- Make necessary changes to make the UI look cleaner.
- Mobile version navbar has bugs. Sometimes it opens, sometimes it doesn't. It isn't responsive properly yet.
- Add title tag to the web pages.
- Add MIT license.
- Redirect the logo to the home page instead of the GitHub repo.
- Add nodemon as a dev dependency for faster development.

**Comment by muskanrastogi1** [comment]
I'd like to take this issue up. Will send a PR by EOD today.

**Comment by akshatvg** [comment]
Solved in https://github.com/CodeChefVIT/Photify-DEVSOC/pull/2
